ALTER TABLE 
    posts
ADD
    COLUMN tags VARCHAR(100) [];

ALTER TABLE 
    posts
ADD
    COLUMN updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();

ALTER TABLE
    posts
ALTER COLUMN created_at SET NOT NULL;
